all:
	coqc GStlc.v
	coqc GStlcExtra.v
	coqc GUnionInter.v
	coqc GUnionInterExtra.v
	coqc GFSubKernel.v
	coqc GFSubKernelExtra.v
	coqc GFSubKernelUnionInter.v
	coqc GFSubKernelUnionInterExtra.v
	coqc GFSubFull.v
	coqc GFSubFullExtra.v
